### ISSUE TITLE
Give regular users the possibility to become admin on the server and mute/kick toxic players

### ISSUE THREAD

**Issue by tuple789** [leighmacdonald/uncletopia#100]
I had session a few days ago where a player was spamming on the voice chat, and even if each user can locally mute him, it still prevented the teamplay over voice chat. Having an admin on the server would help solve this issue as this toxic player could have been muted server side.

**Comment by JONTTM** [comment]
Hello, if you would like to become a moderator, I would recommend becoming a regular on the servers and in the Discord, then messaging Dane on Discord when he makes an announcement about needing more moderators (which probably won’t happen for a while since we have plenty of moderators). 

If you need to report something on the servers, then please join the [Discord](https://discord.gg/uncledane) and mention @Uncletopia Moderator in the [#uncletopia-server](https://discord.com/channels/132353223125106688/722832493648150558) chat.
