### ISSUE TITLE
Add a vote for alltalk

### ISSUE THREAD

**Issue by Arlwiss** [leighmacdonald/uncletopia#127]
All-talk is a feature unique to community servers and helps build community / keep regular visitors to the server and get newer players more involved. The social aspect of community servers is one of their big appeals.

To shake up the often quite competitive nature of Uncletopia all-talk could be introduced to a match via a majority vote from players.

(From lia_rein)

**Comment by UncleDane** [comment]
This issue was discussed in a direct message with Lia_Rein, so I'll just provide the summary of my thoughts as I relayed it to them:

**(...) Alltalk isn't really something I'm interested in adding for the reason you supplied.** ("Most of the arguments against all talk have been pretty easily debatable except for the one where Uncle Dane probably dosnt think its enough like casual.") **People use comms to communicate vital information to their team. If they want to talk with members of the enemy team in a more casual sense, the Discord provides a public voice chat room for that.**

**(...) I suppose I personally find charm in relegating communication with the opposing team to non-verbal interactions like taunting or using the text chat. Combined with the fact that enabling all-talk effectively removes one of the most reliable ways of communicating with your team for teamwork purposes, and I hope you can understand why I think it's best for the intended Uncletopia experience.**
